lacp: fix build failure with inline declaration
Previous commit 336a5584 has a variable declared inline, while
-Wdeclaration-after-statement flag is enabled on this branch. This
causes build failure:

   lib/lacp.c:620:9: error: mixing declarations and code

The declaration of the variable "enable" has been moved in this change
to comply with the expected behavior.

Signed-off-by: Shu Shen <shu.shen@gmail.com>